export const API_ENDPOINTS = {
  _CONVERSATION: {
    GET_CONVERSATION_HISTORY: '/api/conversations/:conversationId/history',
    GET_CONVERSATIONS: '/api/conversations',
  },
  _ESLINT: {
    LINT_CODE: '/api/eslint/lint',
    LINT_DIRECTORY: '/api/eslint/lint-directory',
    LINT_FILES: '/api/eslint/lint-files',
  },
  _FILE: {
    CLOSE_FILE: '/api/file/close',
    COPY_FILE_OR_FOLDER: '/api/file/copy',
    CREATE: '/api/file/create',
    CREATE_FOLDER: '/api/file/create-folder',
    DELETE_FILE: '/api/file/delete',
    DOWNLOAD_FILE: '/api/file/download',
    GET_FILES: '/api/file/list',
    MOVE_FILE_OR_FOLDER: '/api/file/move',
    OPEN_FILE: '/api/file/open',
    PROXY: '/api/file/proxy',
    READ_FILE_CONTENT: '/api/file/read',
    READ_MULTIPLE_FILES: '/api/file/read-many',
    RENAME_FILE_OR_FOLDER: '/api/file/rename',
    SCAN_FILE: '/api/file/scan',
    SEARCH_FILES: '/api/file/search',
    STREAM_FILE: '/api/file/stream',
    UPLOAD_FILE: '/api/file/upload',
    UPLOAD_MULTIPLE_FILES: '/api/file/upload-multiple',
    WRITE_FILE_CONTENT: '/api/file/write',
  },
  _GEMINI_FILE: {
    GENERATE_TEXT: '/api/gemini/file/generate-text',
    GENERATE_TEXT_WITH_BASE64_IMAGE: '/api/gemini/file/generate-image-base64',
    GENERATE_TEXT_WITH_FILE: '/api/gemini/file/generate-file',
    GENERATE_VIDEO: '/api/gemini/file/generate-video',
  },
  _GOOGLE_GEMINI: {
    OPTIMIZE_CODE: '/api/google-gemini/optimize-code',
  },
  _LLM: {
    GENERATE_CONTENT: '/api/llm/generate-llm',
    GET_PROJECT_STRUCTURE: '/api/llm/project-structure',
  },
  _RECORDING: {
    CAPTURE: '/api/recording/capture',
    CLEANUP_OLD: '/api/recording/recordings/cleanup',
    CREATE: '/api/recording',
    FIND_ALL: '/api/recording',
    FIND_ALL_PAGINATED: '/api/recording/paginated',
    FIND_ONE: '/api/recording/:id',
    GET_METADATA: '/api/recording/metadata',
    LIST_RECORDINGS: '/api/recording/list',
    RECORDING_STATUS: '/api/recording/status',
    REMOVE: '/api/recording/:id',
    START: '/api/recording/record-start',
    STOP: '/api/recording/record-stop',
    UPDATE: '/api/recording/:id',
  },
  _UTILS: {
    CONVERT_IMAGE_TO_SVG: '/api/utils/convert-to-svg',
    CONVERT_TO_HTML: '/api/utils/to-html',
    CONVERT_TO_JSON: '/api/utils/to-json',
    CONVERT_TO_MARKDOWN: '/api/utils/to-markdown',
    DETECT_LANGUAGE: '/api/utils/detect-language',
    ENV_TO_JSON: '/api/utils/env-to-json',
    EXTRACT_TITLE: '/api/utils/extract-title',
    FIX_JSON: '/api/utils/json-fix',
    FORMAT_CODE: '/api/utils/format-code',
    GET_DIRECTORY: '/api/utils/get-directory',
    HTML_TO_DOCX: '/api/utils/html-to-docx',
    JSON_TO_ENV: '/api/utils/json-to-env',
    JSON_TO_SQL: '/api/utils/json-to-insert',
    MARKDOWN_TO_DOCX: '/api/utils/markdown-to-docx',
    PARSE_ENV_MAP: '/api/utils/parse-env-map',
    PARSE_INSERT: '/api/utils/parse-insert',
    PARSE_SELECT: '/api/utils/parse-select',
    REMOVE_CODE_COMMENT: '/api/utils/remove-code-comment',
    STRIP_CODE_BLOCK: '/api/utils/strip-code-block',
    TO_PLAIN_TEXT: '/api/utils/markdown-to-plain-text',
  },
} as const;
